#!/bin/bash

. debian/tests/common

defer 'journalctl -u docker | tail'

# make sure Docker itself is working before we go too deep down the rabbit hole
docker version

debootstrap \
	--variant=minbase \
	bionic \
	"$tempDir"

tar -cC "$tempDir" . | docker import - bionic
defer 'docker rmi bionic'

docker run --name test bionic true
defer 'docker rm -f test'
