#!/bin/bash

# XXX This currently doesn't work on the autopkgtest infrastructure,
# networking doesn't work inside the lxc container for some reason.

# XXX It's also a bit of a dodgy test because it tests the archive rather
# than the installed packages like an autopkgtest is supposed to.

if [ -n "$http_proxy" ]; then
    lxc config set core.proxy_http $http_proxy
fi
if [ -n "$https_proxy" ]; then
    lxc config set core.proxy_http $https_proxy
fi
if [ -n "$noproxy" ]; then
    lxc config set core.proxy_ignore_hosts $noproxy
fi

. debian/tests/common

suite=${suite:-$(lsb_release -cs)}

lxc launch ubuntu-daily:${suite} docker -p default -p docker

defer 'lxc delete --force docker'

# XXX This won't work on architectures that are on ports.ubuntu.com
cat <<EOF | lxc file push - docker/etc/apt/sources.list.d/proposed.list
deb http://archive.ubuntu.com/ubuntu ${suite}-proposed main restricted universe multiverse
EOF

attempts=0
while ! lxc file pull docker/etc/resolv.conf - 2> /dev/null | grep -q nameserver; do
    sleep 1
    attempts=$((attempts+1))
    if [ $attempts -gt 30 ]; then
        echo "Network failed to come up after 30 seconds"
        exit 1
    fi
done

lxc exec docker -- apt update
lxc exec docker -- apt dist-upgrade -y
lxc exec docker -- apt install docker.io -y
# Now basically run the simplest possible test inside the container.
lxc exec docker -- docker run alpine:latest true
