#!/bin/bash
set -e

# apply patches
dpkg-source --before-build .

./debian/rules setup-gopath
export GOPATH="$PWD/.gopath:/usr/share/gocode"

export DOCKER_GITCOMMIT="$(./debian/helpers/gitcommit.sh)"

./hack/make.sh test-integration-cli

./debian/rules clean

# unapply patches
dpkg-source --after-build .
