#!/usr/bin/dh-exec

# docker itself
bundles/${DOCKER_VERSION}/${DOCKER_BUILD_TARGET}/docker-${DOCKER_VERSION} => usr/bin/docker

contrib/*-integration usr/share/docker.io/contrib/
contrib/check-config.sh usr/share/docker.io/contrib/
contrib/completion/zsh/_docker usr/share/zsh/vendor-completions/
contrib/init/systemd/docker.socket lib/systemd/system/
contrib/mk* usr/share/docker.io/contrib/
contrib/nuke-graph-directory.sh usr/share/docker.io/contrib/
