#!/bin/sh
set -e

if dpkg-maintscript-helper supports mv_conffile; then
	for conffiles in \
		'/etc/bash_completion.d/docker.io /etc/bash_completion.d/docker' \
		'/etc/default/docker.io /etc/default/docker' \
		'/etc/init.d/docker.io /etc/init.d/docker' \
		'/etc/init/docker.io.conf /etc/init/docker.conf' \
	; do
		dpkg-maintscript-helper mv_conffile $conffiles 1.0.0~dfsg1-1 -- "$@"
	done
fi

#DEBHELPER#
