#!/usr/bin/dh-exec

components/engine/api usr/share/gocode/src/github.com/docker/docker/
components/engine/client usr/share/gocode/src/github.com/docker/docker/
components/engine/dockerversion usr/share/gocode/src/github.com/docker/docker/
components/engine/errdefs usr/share/gocode/src/github.com/docker/docker/
components/engine/image usr/share/gocode/src/github.com/docker/docker/
components/engine/oci usr/share/gocode/src/github.com/docker/docker/
components/engine/opts usr/share/gocode/src/github.com/docker/docker/
components/engine/pkg usr/share/gocode/src/github.com/docker/docker/
components/engine/registry usr/share/gocode/src/github.com/docker/docker/
components/engine/rootless usr/share/gocode/src/github.com/docker/docker/
components/engine/vendor usr/share/gocode/src/github.com/docker/docker/
components/cli/cli usr/share/gocode/src/github.com/docker/cli/
components/cli/opts usr/share/gocode/src/github.com/docker/cli/
