#!/usr/bin/dh-exec

engine/api usr/share/gocode/src/github.com/docker/docker/
engine/client usr/share/gocode/src/github.com/docker/docker/
engine/dockerversion usr/share/gocode/src/github.com/docker/docker/
engine/errdefs usr/share/gocode/src/github.com/docker/docker/
engine/image usr/share/gocode/src/github.com/docker/docker/
engine/oci usr/share/gocode/src/github.com/docker/docker/
engine/opts usr/share/gocode/src/github.com/docker/docker/
engine/pkg usr/share/gocode/src/github.com/docker/docker/
engine/registry usr/share/gocode/src/github.com/docker/docker/
engine/rootless usr/share/gocode/src/github.com/docker/docker/
engine/vendor usr/share/gocode/src/github.com/docker/docker/
cli/cli usr/share/gocode/src/github.com/docker/cli/
cli/opts usr/share/gocode/src/github.com/docker/cli/
